#pragma once
#include "mfem.hpp"
#include "mpi.h"
#include "../include/SimulationConfig.hpp"
#include "../include/Utils.hpp"
#include "../include/Constants.hpp"
#include "../include/SimTypes.hpp"
#include "../include/Initialize_Geometry.hpp"
#include "../include/Domain_Parameters.hpp"
#include "../include/Concentrations_Base.hpp"
#include "../include/Potentials_Base.hpp"
#include "../include/CnA.hpp"
// #include "../include/CnC.hpp"
#include "../include/CnE.hpp"
#include "../include/PotA.hpp"
#include "../include/PotC.hpp"
#include "../include/PotE.hpp"
#include "../include/Reaction.hpp"
#include "../include/Adjust.hpp"
#include "../include/BoundaryConditions.hpp"
#include "../include/SimulationState.hpp"
#include "../include/MaterialProperties.hpp"
#include "../include/ElectrodeDiffusion.hpp"

