BESFEM: src/battery_simulation.cpp File Reference
battery_simulation.cpp File Reference
#include "mfem.hpp"
#include "mpi.h"
#include "../include/BESFEM_All.hpp"
#include <chrono>
#include <iostream>
#include <cmath>
#include <filesystem>
#include <iomanip>
#include <sstream>
#include <ctime>
#include <vector>
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 14 of file battery_simulation.cpp.
References sim::ANODE, SimulationState::anode_out, SimulationState::anode_particles, SimulationState::anode_potential, Domain_Parameters::AvEs, sim::BOTH, Utils::BuildRunOutdir(), sim::CATHODE, SimulationState::cathode_out, SimulationState::cathode_particles, SimulationState::cathode_potential, SimulationState::CnE_gf, Initialize_Geometry::combine_particle_groups, SimulationConfig::combine_particle_groups, SimulationConfig::Cr, SimulationConfig::dh, SimulationConfig::dsF_file_A, SimulationConfig::dsF_file_C, SimulationConfig::dt, SimulationState::electrolyte_concentration, SimulationState::electrolyte_potential, sim::FULL, SimulationConfig::gc, Domain_Parameters::gtPs, Domain_Parameters::gtPse, Domain_Parameters::gTrgPs, sim::HALF, SimulationConfig::half_electrode, InitializeFields(), Initialize_Geometry::InitializeMesh(), SimulationConfig::mesh_file, SimulationConfig::mesh_type, SimulationConfig::mode, SimulationConfig::num_timesteps, SimulationConfig::order, Pairs(), ParseSimulationArgs(), SimulationState::phA_gf, SimulationState::phC_gf, SimulationState::phE_gf, Domain_Parameters::ps, Domain_Parameters::pse, Domain_Parameters::psi, SimulationState::Rxn_gf, Utils::SaveSimulationSnapshotMulti(), BoundaryConditions::SetupBoundaryConditions(), Domain_Parameters::SetupDomainParameters(), sim::STEPS, SimulationConfig::stop_mode, UpdateAnodePairChemicalPotentials(), UpdateCathodePairChemicalPotentials(), ValidateConfig(), SimulationConfig::VCut, sim::VOLTAGE, SimulationConfig::Vsr0, and Domain_Parameters::WeightEs.