BESFEM: ElectrodeDiffusion Class Reference
ElectrodeDiffusion Class Reference
Solves solid-state lithium diffusion within electrode particles.
#include <ElectrodeDiffusion.hpp>
Public Member Functions
ElectrodeDiffusion (Initialize_Geometry &geo, Domain_Parameters &para, sim::MaterialType mat, const SimulationConfig &cfg)
Construct a diffusion-based electrode concentration solver.
void SetupField (mfem::ParGridFunction &Cn, double initial_value, mfem::ParGridFunction &psx, double gtPsx)
Initialize the diffusion solver.
void UpdateConcentration (mfem::ParGridFunction &Rx, mfem::ParGridFunction &Cn, mfem::ParGridFunction &psx, double gtPsx, mfem::ParGridFunction &weight_elec, const std::vector< ConcentrationBase::PairCoupling > &pair_terms)
Advance the concentration field by one timestep.
Public Member Functions inherited from ConcentrationBase
ConcentrationBase (Initialize_Geometry &geo, Domain_Parameters &para, sim::MaterialType mat, const SimulationConfig &cfg)
Construct the base concentration solver.
virtual ~ConcentrationBase ()=default
Virtual destructor for safe cleanup through base-class pointers.
virtual void SetupField (mfem::ParGridFunction &Cn, double initial_value, mfem::ParGridFunction &psx, double gtPsx)=0
Initialize a concentration field and assemble model-specific data.
virtual void UpdateConcentration (mfem::ParGridFunction &Rx, mfem::ParGridFunction &Cn, mfem::ParGridFunction &psx, double gtPsx, mfem::ParGridFunction &weight_elec, const std::vector< PairCoupling > &pair_terms)=0
Advance the concentration field by one timestep.
virtual void SaltConservation (mfem::ParGridFunction &Cn, mfem::ParGridFunction &psx)
Apply salt or concentration conservation correction.
double GetLithiation () const
Return the current global lithiation or concentration fraction.
Public Attributes
const SimulationConfig & cfg
Reference to the simulation configuration.
Public Attributes inherited from ConcentrationBase
double Xfr = 0.0
Global degree of lithiation or concentration.
double CeC = 0.0
Local (per-element) salt or concentration moment.
double gCeC = 0.0
Global salt inventory (summed over domain).
double CeAvg = 0.0
Global average concentration.
double Ce0 = 0.001
Initial background concentration (reference).
mfem::Array< double > VtxVal
Vertex-value workspace buffer.
int nE = 0
Number of mesh elements.
int nC = 0
Number of nodes per element (corners).
int nV = 0
Total number of global vertices.
mfem::Vector EAvg
Per-element averages (workspace).
const mfem::Vector & EVol
Element volumes (from Domain_Parameters).
double gtPsi = 0.0
Global ψ normalization (total).
double gtPse = 0.0
Global ψ normalization (electrolyte or solid).
mfem::Array< int > boundary_dofs
Boundary true DOFs.
mfem::HypreParVector X1v
Scratch vector for assembly/solves.
Initialize_Geometry & geometry
Reference to geometry data, including mesh and FE-space information.
Domain_Parameters & domain_parameters
Reference to global simulation fields and domain parameters.
const SimulationConfig & cfg
Reference to user-defined simulation settings.
std::shared_ptr< mfem::ParFiniteElementSpace > fespace
Shared parallel finite element space.
FEMOperators fem
Shared finite element helper operators.
Utils utils
Utility helper object for common postprocessing and calculations.
mfem::ParMesh * pmesh = nullptr
Parallel mesh (distributed).
mfem::Mesh * gmesh = nullptr
Global serial mesh (rank 0, if available).
std::unique_ptr< mfem::ParGridFunction > TmpF
Temporary grid-function buffer.
Private Attributes
mfem::ParGridFunction Dp
Diffusivity field.
mfem::ParGridFunction Rxn
Reaction/source field.
mfem::HypreParVector PsVc
Phase-field true-DOF vector.
mfem::HypreParVector CpV0
Previous concentration vector.
mfem::HypreParVector RHCp
Right-hand side vector.
mfem::HypreParVector CpVn
Updated concentration vector.
std::unique_ptr< mfem::ParBilinearForm > Mt
Mass bilinear form.
mfem::HypreParMatrix Mmatp
Mass matrix.
mfem::CGSolver Mp_solver
Diffusion linear solver.
mfem::HypreSmoother Mp_prec
Solver preconditioner.
std::unique_ptr< mfem::ParBilinearForm > Kc2
Diffusion bilinear form.
mfem::HypreParMatrix Kmatp
Diffusion stiffness matrix.
std::unique_ptr< mfem::ParLinearForm > Bc2
Linear-form assembly.
mfem::HypreParVector Fcb
Boundary/source contribution vector.
mfem::ParLinearForm Fct
Source-term linear form.
mfem::GridFunctionCoefficient cAp
Reaction-field coefficient.
mfem::GridFunctionCoefficient cDp
Diffusivity coefficient.
std::unique_ptr< mfem::HypreParMatrix > Tmatp
System matrix.
double gtPsC = 0.0
Global particle phase-field integral.
double gtPsi = 0.0
Global solid phase-field integral.
bool combine_particle_groups = false
Combine all particles into a single diffusion solve.
Additional Inherited Members
Protected Attributes inherited from ConcentrationBase
sim::MaterialType material
Material type associated with this concentration solver.
Detailed Description
Solves solid-state lithium diffusion within electrode particles.
ElectrodeDiffusion updates the lithium concentration in electrode particles using a diffusion equation with electrochemical reaction coupling at the particle/electrolyte interface.
The class assembles the finite-element operators required for the diffusion solve, evaluates concentration-dependent material properties, and advances the particle concentration at each timestep.
Definition at line 29 of file ElectrodeDiffusion.hpp.
Constructor & Destructor Documentation
ElectrodeDiffusion()
ElectrodeDiffusion::ElectrodeDiffusion (Initialize_Geometry & geo, Domain_Parameters & para, sim::MaterialType mat, const SimulationConfig & cfg)
Construct a diffusion-based electrode concentration solver.
Parameters
geo Reference to the initialized geometry object.
para Reference to the domain parameter object.
mat Material type associated with this electrode.
cfg Reference to the simulation configuration.
Definition at line 8 of file ElectrodeDiffusion.cpp.
Member Function Documentation
SetupField()
void ElectrodeDiffusion::SetupField (mfem::ParGridFunction & Cn, double initial_value, mfem::ParGridFunction & psx, double gtPsx) virtual
Initialize the diffusion solver.
Initializes the concentration field, applies the phase-field mask, and assembles the finite-element operators required for the diffusion equation.
Parameters
Cn Concentration field to initialize.
initial_value Initial lithium concentration.
psx Particle phase-field mask.
gtPsx Global integral of the phase-field mask.
Implements ConcentrationBase.
Definition at line 13 of file ElectrodeDiffusion.cpp.
References ConcentrationBase::boundary_dofs, Utils::CalculateLithiation(), cDp, ConcentrationBase::fem, FEMOperators::FormSystemMatrix(), Utils::GetLithiation(), FEMOperators::InitializeMassMatrix(), FEMOperators::InitializeStiffnessMatrix(), Kc2, Mmatp, Mp_prec, Mp_solver, Mt, PsVc, Utils::SetInitialValue(), FEMOperators::SolverConditions(), ConcentrationBase::utils, and ConcentrationBase::Xfr.
UpdateConcentration()
void ElectrodeDiffusion::UpdateConcentration (mfem::ParGridFunction & Rx, mfem::ParGridFunction & Cn, mfem::ParGridFunction & psx, double gtPsx, mfem::ParGridFunction & weight_elec, const std::vector< ConcentrationBase::PairCoupling > & pair_terms) virtual
Advance the concentration field by one timestep.
Solves the diffusion equation, including electrochemical reaction source terms and optional particle-particle coupling contributions.
Parameters
Rx Reaction/source term field.
Cn Concentration field to update.
psx Particle phase-field mask.
gtPsx Global integral of the phase-field mask.
weight_elec Electrolyte-interface weighting field.
pair_terms Pairwise particle coupling workspaces.
Implements ConcentrationBase.
Definition at line 39 of file ElectrodeDiffusion.cpp.
References Bc2, ConcentrationBase::boundary_dofs, Utils::CalculateLithiation(), cAp, cDp, cfg, combine_particle_groups, Utils::ComputePairFlux(), CpV0, CpVn, MaterialProperties::Diffusivity(), Dp, SimulationConfig::dt, Fcb, Fct, ConcentrationBase::fem, FEMOperators::FormLinearSystem(), Utils::GetLithiation(), FEMOperators::InitializeForceTerm(), Utils::InitializeReaction(), Kc2, Kmatp, ConcentrationBase::material, Mmatp, Mp_solver, ConcentrationBase::nV, PsVc, RHCp, Rxn, MaterialProperties::SiteDensity(), Tmatp, FEMOperators::Update(), ConcentrationBase::utils, ConcentrationBase::X1v, and ConcentrationBase::Xfr.
Member Data Documentation
Bc2
std::unique_ptr<mfem::ParLinearForm> ElectrodeDiffusion::Bc2 private
Linear-form assembly.
Definition at line 93 of file ElectrodeDiffusion.hpp.
Referenced by UpdateConcentration().
cAp
mfem::GridFunctionCoefficient ElectrodeDiffusion::cAp private
Reaction-field coefficient.
Definition at line 98 of file ElectrodeDiffusion.hpp.
Referenced by UpdateConcentration().
cDp
mfem::GridFunctionCoefficient ElectrodeDiffusion::cDp private
Diffusivity coefficient.
Definition at line 99 of file ElectrodeDiffusion.hpp.
Referenced by SetupField(), and UpdateConcentration().
cfg
const SimulationConfig& ElectrodeDiffusion::cfg
Reference to the simulation configuration.
Definition at line 72 of file ElectrodeDiffusion.hpp.
Referenced by UpdateConcentration().
combine_particle_groups
bool ElectrodeDiffusion::combine_particle_groups = false private
Combine all particles into a single diffusion solve.
Definition at line 106 of file ElectrodeDiffusion.hpp.
Referenced by UpdateConcentration().
CpV0
mfem::HypreParVector ElectrodeDiffusion::CpV0 private
Previous concentration vector.
Definition at line 80 of file ElectrodeDiffusion.hpp.
Referenced by UpdateConcentration().
CpVn
mfem::HypreParVector ElectrodeDiffusion::CpVn private
Updated concentration vector.
Definition at line 82 of file ElectrodeDiffusion.hpp.
Referenced by UpdateConcentration().
Dp
mfem::ParGridFunction ElectrodeDiffusion::Dp private
Diffusivity field.
Definition at line 76 of file ElectrodeDiffusion.hpp.
Referenced by UpdateConcentration().
Fcb
mfem::HypreParVector ElectrodeDiffusion::Fcb private
Boundary/source contribution vector.
Definition at line 95 of file ElectrodeDiffusion.hpp.
Referenced by UpdateConcentration().
Fct
mfem::ParLinearForm ElectrodeDiffusion::Fct private
Source-term linear form.
Definition at line 96 of file ElectrodeDiffusion.hpp.
Referenced by UpdateConcentration().
gtPsC
double ElectrodeDiffusion::gtPsC = 0.0 private
Global particle phase-field integral.
Definition at line 103 of file ElectrodeDiffusion.hpp.
gtPsi
double ElectrodeDiffusion::gtPsi = 0.0 private
Global solid phase-field integral.
Definition at line 104 of file ElectrodeDiffusion.hpp.
Kc2
std::unique_ptr<mfem::ParBilinearForm> ElectrodeDiffusion::Kc2 private
Diffusion bilinear form.
Definition at line 90 of file ElectrodeDiffusion.hpp.
Referenced by SetupField(), and UpdateConcentration().
Kmatp
mfem::HypreParMatrix ElectrodeDiffusion::Kmatp private
Diffusion stiffness matrix.
Definition at line 91 of file ElectrodeDiffusion.hpp.
Referenced by UpdateConcentration().
Mmatp
mfem::HypreParMatrix ElectrodeDiffusion::Mmatp private
Mass matrix.
Definition at line 85 of file ElectrodeDiffusion.hpp.
Referenced by SetupField(), and UpdateConcentration().
Mp_prec
mfem::HypreSmoother ElectrodeDiffusion::Mp_prec private
Solver preconditioner.
Definition at line 88 of file ElectrodeDiffusion.hpp.
Referenced by SetupField().
Mp_solver
mfem::CGSolver ElectrodeDiffusion::Mp_solver private
Diffusion linear solver.
Definition at line 87 of file ElectrodeDiffusion.hpp.
Referenced by SetupField(), and UpdateConcentration().
Mt
std::unique_ptr<mfem::ParBilinearForm> ElectrodeDiffusion::Mt private
Mass bilinear form.
Definition at line 84 of file ElectrodeDiffusion.hpp.
Referenced by SetupField().
PsVc
mfem::HypreParVector ElectrodeDiffusion::PsVc private
Phase-field true-DOF vector.
Definition at line 79 of file ElectrodeDiffusion.hpp.
Referenced by SetupField(), and UpdateConcentration().
RHCp
mfem::HypreParVector ElectrodeDiffusion::RHCp private
Right-hand side vector.
Definition at line 81 of file ElectrodeDiffusion.hpp.
Referenced by UpdateConcentration().
Rxn
mfem::ParGridFunction ElectrodeDiffusion::Rxn private
Reaction/source field.
Definition at line 77 of file ElectrodeDiffusion.hpp.
Referenced by UpdateConcentration().
Tmatp
std::unique_ptr<mfem::HypreParMatrix> ElectrodeDiffusion::Tmatp private
System matrix.
Definition at line 101 of file ElectrodeDiffusion.hpp.
Referenced by UpdateConcentration().
The documentation for this class was generated from the following files:
include/ElectrodeDiffusion.hpp
src/ElectrodeDiffusion.cpp