BESFEM: Utils Class Reference
Utils Class Reference
Helper class for common BESFEM operations.
#include <Utils.hpp>
Public Member Functions
Utils (Initialize_Geometry &geo, Domain_Parameters &para, const SimulationConfig &cfg)
Construct a Utils helper object.
void SetInitialValue (mfem::ParGridFunction &Cn, double initial_value)
Set a concentration field to a uniform initial value.
void InitializeReaction (mfem::ParGridFunction &Rx1, mfem::ParGridFunction &Rx2, double value)
Initialize two reaction fields.
void InitializeReaction (mfem::ParGridFunction &Rx1, mfem::ParGridFunction &Rx2, mfem::ParGridFunction &Rx3, double value)
Initialize three reaction fields.
void CalculateLithiation (mfem::ParGridFunction &Cn, mfem::ParGridFunction &psx, double gtps)
Compute the global lithiation or concentration fraction.
void CalculateReactionInfx (mfem::ParGridFunction &Rx, double &xCrnt)
Compute the global reaction current.
void ComputePairFlux (mfem::ParGridFunction &sum_part, mfem::ParGridFunction &weight, mfem::ParGridFunction &grad_psi, mfem::ParGridFunction &mu_self, mfem::ParGridFunction &mu_nbr)
Compute pairwise particle flux from chemical-potential differences.
void CalculateGlobalError (mfem::ParGridFunction &px0, mfem::ParGridFunction &potential, mfem::ParGridFunction &psx, double &globalerror, double gtPsx)
Compute the global error between two potential fields.
double GetLithiation () const
Return the most recently computed lithiation fraction.
Static Public Member Functions
static std::string BuildRunOutdir (const char *mesh_file, int num_steps)
Build a timestamped output directory path.
static void SaveSimulationSnapshot (int t, const std::string &outdir, Initialize_Geometry &geometry, Domain_Parameters &domain_parameters, mfem::ParGridFunction &phA, mfem::ParGridFunction &phC, mfem::ParGridFunction &phE, mfem::ParGridFunction &CnA, mfem::ParGridFunction &CnC, mfem::ParGridFunction &CnE, mfem::ParGridFunction &CnApsi, mfem::ParGridFunction &CnCpsi, mfem::ParGridFunction &CnEpsi, mfem::ParGridFunction &CnP, int save_interval=500)
Save a full-cell simulation snapshot.
static void SaveSimulationSnapshot (int t, const std::string &outdir, Initialize_Geometry &geometry, Domain_Parameters &domain_parameters, mfem::ParGridFunction &phC, mfem::ParGridFunction &phE, mfem::ParGridFunction &CnC, mfem::ParGridFunction &CnE, mfem::ParGridFunction &CnCpsi, mfem::ParGridFunction &CnEpsi, int save_interval=500)
Save a half-cell simulation snapshot.
static void SaveSimulationSnapshotMulti (int t, const std::string &outdir, Initialize_Geometry &geometry, Domain_Parameters &domain_parameters, const std::vector< mfem::ParGridFunction * > &particle_cn, std::vector< std::unique_ptr< mfem::ParGridFunction > > &particle_out, int save_interval=1000)
Save particle-resolved concentration snapshots.
Private Attributes
Initialize_Geometry & geometry_
Geometry handler.
Domain_Parameters & domain_
Domain-parameter object.
const SimulationConfig & cfg
Simulation configuration.
mfem::ParMesh * pmesh_ = nullptr
Parallel mesh pointer.
std::shared_ptr< mfem::ParFiniteElementSpace > fes_
Parallel finite element space.
int nE_ = 0
Number of elements.
int nC_ = 0
Number of nodes per element.
int nV_ = 0
Number of vertices.
mfem::Vector EVol_
Element volumes.
mfem::Vector EAvg_
Per-element average workspace.
mfem::Array< double > VtxVal_
Vertex-value workspace.
mfem::ParGridFunction TmpF_
Temporary grid-function workspace.
double Xfr_ = 0.0
Most recently computed lithiation fraction.
double geCrnt_ = 0.0
Global reaction current.
double infx_ = 0.0
Integrated flux/current diagnostic.
Detailed Description
Helper class for common BESFEM operations.
Utils provides shared routines for initializing fields, computing lithiation and reaction currents, evaluating global errors, computing pairwise flux terms, and saving simulation snapshots.
Definition at line 29 of file Utils.hpp.
Constructor & Destructor Documentation
Utils()
Utils::Utils (Initialize_Geometry & geo, Domain_Parameters & para, const SimulationConfig & cfg)
Construct a Utils helper object.
Parameters
geo Reference to the geometry handler.
para Reference to the domain-parameter object.
cfg Reference to the simulation configuration.
Definition at line 8 of file Utils.cpp.
Member Function Documentation
BuildRunOutdir()
static std::string Utils::BuildRunOutdir (const char * mesh_file, int num_steps) inline static
Build a timestamped output directory path.
Parameters
mesh_file Path to the mesh file.
num_steps Number of timesteps.
Returns
Output directory path.
Definition at line 139 of file Utils.hpp.
Referenced by main().
CalculateGlobalError()
void Utils::CalculateGlobalError (mfem::ParGridFunction & px0, mfem::ParGridFunction & potential, mfem::ParGridFunction & psx, double & globalerror, double gtPsx)
Compute the global error between two potential fields.
Parameters
px0 Previous potential field.
potential Updated potential field.
psx Phase-field mask.
globalerror Output global error.
gtPsx Global integral of the phase-field mask.
Definition at line 73 of file Utils.cpp.
References TmpF_.
Referenced by ElectrodePotential::UpdatePotential(), ElectrolytePotential::UpdatePotential(), and ElectrolytePotential::UpdatePotential().
CalculateLithiation()
void Utils::CalculateLithiation (mfem::ParGridFunction & Cn, mfem::ParGridFunction & psx, double gtps)
Compute the global lithiation or concentration fraction.
Parameters
Cn Concentration field.
psx Phase-field mask.
gtps Global integral of the phase-field mask.
Definition at line 28 of file Utils.cpp.
References EAvg_, EVol_, nC_, nE_, TmpF_, VtxVal_, and Xfr_.
Referenced by ElectrodeCahnHilliard::SetupField(), ElectrodeDiffusion::SetupField(), ElectrodeCahnHilliard::UpdateConcentration(), and ElectrodeDiffusion::UpdateConcentration().
CalculateReactionInfx()
void Utils::CalculateReactionInfx (mfem::ParGridFunction & Rx, double & xCrnt)
Compute the global reaction current.
Parameters
Rx Reaction field.
xCrnt Output global reaction current.
Definition at line 48 of file Utils.cpp.
References EAvg_, EVol_, geCrnt_, infx_, nC_, nE_, pmesh_, and VtxVal_.
Referenced by ElectrolyteDiffusion::UpdateConcentration().
ComputePairFlux()
void Utils::ComputePairFlux (mfem::ParGridFunction & sum_part, mfem::ParGridFunction & weight, mfem::ParGridFunction & grad_psi, mfem::ParGridFunction & mu_self, mfem::ParGridFunction & mu_nbr)
Compute pairwise particle flux from chemical-potential differences.
Parameters
sum_part Output accumulated pair flux field.
weight Pairwise coupling weight.
grad_psi Pairwise interface/gradient field.
mu_self Chemical potential of the current particle.
mu_nbr Chemical potential of the neighboring particle.
Definition at line 86 of file Utils.cpp.
References SimulationConfig::cathode_materials, cfg, nV_, Constants::Perm, Constants::RT, and MaterialProperties::SiteDensity().
Referenced by ElectrodeCahnHilliard::UpdateConcentration(), and ElectrodeDiffusion::UpdateConcentration().
GetLithiation()
double Utils::GetLithiation () const inline
Return the most recently computed lithiation fraction.
Returns
Lithiation or concentration fraction.
Definition at line 130 of file Utils.hpp.
References Xfr_.
Referenced by ElectrodeCahnHilliard::SetupField(), ElectrodeDiffusion::SetupField(), ElectrodeCahnHilliard::UpdateConcentration(), and ElectrodeDiffusion::UpdateConcentration().
InitializeReaction() [1/2]
void Utils::InitializeReaction (mfem::ParGridFunction & Rx1, mfem::ParGridFunction & Rx2, double value)
Initialize two reaction fields.
Parameters
Rx1 First reaction field.
Rx2 Second reaction field.
value Initial value.
Definition at line 15 of file Utils.cpp.
Referenced by ElectrodeCahnHilliard::UpdateConcentration(), ElectrodeDiffusion::UpdateConcentration(), and ElectrolyteDiffusion::UpdateConcentration().
InitializeReaction() [2/2]
void Utils::InitializeReaction (mfem::ParGridFunction & Rx1, mfem::ParGridFunction & Rx2, mfem::ParGridFunction & Rx3, double value)
Initialize three reaction fields.
Parameters
Rx1 First reaction field.
Rx2 Second reaction field.
Rx3 Third reaction field.
value Initial value.
Definition at line 21 of file Utils.cpp.
SaveSimulationSnapshot() [1/2]
void Utils::SaveSimulationSnapshot (int t, const std::string & outdir, Initialize_Geometry & geometry, Domain_Parameters & domain_parameters, mfem::ParGridFunction & phA, mfem::ParGridFunction & phC, mfem::ParGridFunction & phE, mfem::ParGridFunction & CnA, mfem::ParGridFunction & CnC, mfem::ParGridFunction & CnE, mfem::ParGridFunction & CnApsi, mfem::ParGridFunction & CnCpsi, mfem::ParGridFunction & CnEpsi, mfem::ParGridFunction & CnP, int save_interval = 500) static
Save a full-cell simulation snapshot.
Parameters
t Timestep index.
outdir Output directory.
geometry Geometry handler.
domain_parameters Domain-parameter object.
phA Anode potential field.
phC Cathode potential field.
phE Electrolyte potential field.
CnA Anode concentration field.
CnC Cathode concentration field.
CnE Electrolyte concentration field.
CnApsi Masked anode concentration field.
CnCpsi Masked cathode concentration field.
CnEpsi Masked electrolyte concentration field.
CnP Combined particle concentration field.
save_interval Number of timesteps between saved snapshots.
Definition at line 103 of file Utils.cpp.
References Initialize_Geometry::parallelMesh, Domain_Parameters::psA, Domain_Parameters::psC, Domain_Parameters::pse, and Domain_Parameters::psi.
SaveSimulationSnapshot() [2/2]
void Utils::SaveSimulationSnapshot (int t, const std::string & outdir, Initialize_Geometry & geometry, Domain_Parameters & domain_parameters, mfem::ParGridFunction & phC, mfem::ParGridFunction & phE, mfem::ParGridFunction & CnC, mfem::ParGridFunction & CnE, mfem::ParGridFunction & CnCpsi, mfem::ParGridFunction & CnEpsi, int save_interval = 500) static
Save a half-cell simulation snapshot.
Parameters
t Timestep index.
outdir Output directory.
geometry Geometry handler.
domain_parameters Domain-parameter object.
phC Electrode potential field.
phE Electrolyte potential field.
CnC Electrode concentration field.
CnE Electrolyte concentration field.
CnCpsi Masked electrode concentration field.
CnEpsi Masked electrolyte concentration field.
save_interval Number of timesteps between saved snapshots.
Definition at line 143 of file Utils.cpp.
References Initialize_Geometry::parallelMesh, Domain_Parameters::pse, and Domain_Parameters::psi.
SaveSimulationSnapshotMulti()
void Utils::SaveSimulationSnapshotMulti (int t, const std::string & outdir, Initialize_Geometry & geometry, Domain_Parameters & domain_parameters, const std::vector< mfem::ParGridFunction * > & particle_cn, std::vector< std::unique_ptr< mfem::ParGridFunction > > & particle_out, int save_interval = 1000) static
Save particle-resolved concentration snapshots.
Parameters
t Timestep index.
outdir Output directory.
geometry Geometry handler.
domain_parameters Domain-parameter object.
particle_cn Particle concentration fields to save.
particle_out Output workspaces for masked/saved fields.
save_interval Number of timesteps between saved snapshots.
Definition at line 179 of file Utils.cpp.
References Initialize_Geometry::parallelMesh, Initialize_Geometry::parfespace, Domain_Parameters::ps, Domain_Parameters::pse, and Domain_Parameters::psi.
Referenced by main().
SetInitialValue()
void Utils::SetInitialValue (mfem::ParGridFunction & Cn, double initial_value)
Set a concentration field to a uniform initial value.
Parameters
Cn Concentration field to initialize.
initial_value Value assigned to the field.
Definition at line 173 of file Utils.cpp.
Referenced by ElectrolytePotential::SetupField(), ElectrodeCahnHilliard::SetupField(), ElectrodeDiffusion::SetupField(), ElectrolyteDiffusion::SetupField(), and ElectrodePotential::SetupField().
Member Data Documentation
cfg
const SimulationConfig& Utils::cfg private
Simulation configuration.
Definition at line 238 of file Utils.hpp.
Referenced by ComputePairFlux().
domain_
Domain_Parameters& Utils::domain_ private
Domain-parameter object.
Definition at line 236 of file Utils.hpp.
EAvg_
mfem::Vector Utils::EAvg_ private
Per-element average workspace.
Definition at line 248 of file Utils.hpp.
Referenced by CalculateLithiation(), and CalculateReactionInfx().
EVol_
mfem::Vector Utils::EVol_ private
Element volumes.
Definition at line 247 of file Utils.hpp.
Referenced by CalculateLithiation(), and CalculateReactionInfx().
fes_
std::shared_ptr<mfem::ParFiniteElementSpace> Utils::fes_ private
Parallel finite element space.
Definition at line 241 of file Utils.hpp.
geCrnt_
double Utils::geCrnt_ = 0.0 private
Global reaction current.
Definition at line 254 of file Utils.hpp.
Referenced by CalculateReactionInfx().
geometry_
Initialize_Geometry& Utils::geometry_ private
Geometry handler.
Definition at line 235 of file Utils.hpp.
infx_
double Utils::infx_ = 0.0 private
Integrated flux/current diagnostic.
Definition at line 255 of file Utils.hpp.
Referenced by CalculateReactionInfx().
nC_
int Utils::nC_ = 0 private
Number of nodes per element.
Definition at line 244 of file Utils.hpp.
Referenced by CalculateLithiation(), and CalculateReactionInfx().
nE_
int Utils::nE_ = 0 private
Number of elements.
Definition at line 243 of file Utils.hpp.
Referenced by CalculateLithiation(), and CalculateReactionInfx().
nV_
int Utils::nV_ = 0 private
Number of vertices.
Definition at line 245 of file Utils.hpp.
Referenced by ComputePairFlux().
pmesh_
mfem::ParMesh* Utils::pmesh_ = nullptr private
Parallel mesh pointer.
Definition at line 240 of file Utils.hpp.
Referenced by CalculateReactionInfx().
TmpF_
mfem::ParGridFunction Utils::TmpF_ private
Temporary grid-function workspace.
Definition at line 251 of file Utils.hpp.
Referenced by CalculateGlobalError(), and CalculateLithiation().
VtxVal_
mfem::Array<double> Utils::VtxVal_ private
Vertex-value workspace.
Definition at line 249 of file Utils.hpp.
Referenced by CalculateLithiation(), and CalculateReactionInfx().
Xfr_
double Utils::Xfr_ = 0.0 private
Most recently computed lithiation fraction.
Definition at line 253 of file Utils.hpp.
Referenced by CalculateLithiation(), and GetLithiation().
The documentation for this class was generated from the following files:
include/Utils.hpp
src/Utils.cpp