BESFEM: FEMOperators Class Reference
FEMOperators Class Reference
Utility class for constructing and manipulating FEM operators in BESFEM.
#include <FEMOperators.hpp>
Public Member Functions
FEMOperators (std::shared_ptr< mfem::ParFiniteElementSpace > fespace)
Construct FEMOperators using a shared FE space.
FEMOperators (mfem::ParFiniteElementSpace *fespace)
Construct FEMOperators from a raw FE space pointer.
~FEMOperators ()
Destructor.
void InitializeMassMatrix (mfem::Coefficient &coef, std::unique_ptr< mfem::ParBilinearForm > &M)
Initialize a mass bilinear form.
void InitializeStiffnessMatrix (mfem::Coefficient &coef, std::unique_ptr< mfem::ParBilinearForm > &K)
Initialize a stiffness bilinear form.
void InitializeForceTerm (mfem::Coefficient &coef, std::unique_ptr< mfem::ParLinearForm > &B)
Initialize a force (linear) form.
void FormSystemMatrix (std::unique_ptr< mfem::ParBilinearForm > &M, mfem::Array< int > &boundary_dofs, mfem::HypreParMatrix &A)
Form the Hypre system matrix from a bilinear form.
void FormLinearSystem (std::unique_ptr< mfem::ParBilinearForm > &K, mfem::Array< int > &boundary_dofs, mfem::ParGridFunction &x, mfem::ParLinearForm &b, mfem::HypreParMatrix &A, mfem::HypreParVector &X, mfem::HypreParVector &B)
Form the linear system A·X = B.
void SolverConditions (mfem::HypreParMatrix &Mmat, mfem::CGSolver &solver, mfem::Solver &preconditioner)
Configure solver and preconditioner for a given system matrix.
void SolverConditions (mfem::CGSolver &solver, mfem::Solver &preconditioner)
Configure solver/preconditioner pair (matrix-free).
void Update (std::unique_ptr< mfem::ParLinearForm > &B)
Reassemble a ParLinearForm.
void Update (std::unique_ptr< mfem::ParBilinearForm > &B)
Reassemble a ParBilinearForm.
Public Attributes
std::shared_ptr< mfem::ParBilinearForm > K
Assembled stiffness form.
mfem::HypreParVector X1v
Scratch true-DoF vector.
mfem::Array< int > boundary_dofs
Essential boundary DOFs.
Private Attributes
mfem::ParMesh * pmesh = nullptr
Parallel mesh.
std::shared_ptr< mfem::ParFiniteElementSpace > fespace
FE space (shared_ptr).
mfem::ParFiniteElementSpace * raw_fespace = nullptr
Raw FE space pointer.
mfem::ParFiniteElementSpace * local_fespace = nullptr
Local FE space (alias).
mfem::ParBilinearForm * M = nullptr
Mass matrix (raw pointer).
std::unique_ptr< mfem::ParLinearForm > B
Force/forcing term.
mfem::ParGridFunction * temp_ps = nullptr
Temporary phase-field grid-function.
mfem::GridFunctionCoefficient * coef = nullptr
Coefficient wrapper for grid-functions.
Detailed Description
Utility class for constructing and manipulating FEM operators in BESFEM.
Provides reusable routines for:
Mass and stiffness matrix assembly (ParBilinearForm)
Force/forcing term assembly (ParLinearForm)
Forming system matrices with essential boundary conditions
Assembling linear systems (A, X, B) for Hypre solvers
Setting solver and preconditioner options
This class centralizes common MFEM assembly tasks used by CnA, CnC, and CnE to reduce duplication across the concentration solvers.
Definition at line 28 of file FEMOperators.hpp.
Constructor & Destructor Documentation
FEMOperators() [1/2]
FEMOperators::FEMOperators (std::shared_ptr< mfem::ParFiniteElementSpace > fespace)
Construct FEMOperators using a shared FE space.
Parameters
fespace Parallel finite element space (shared_ptr).
Definition at line 14 of file FEMOperators.cpp.
FEMOperators() [2/2]
FEMOperators::FEMOperators (mfem::ParFiniteElementSpace * fespace)
Construct FEMOperators from a raw FE space pointer.
Parameters
fespace Raw pointer to a parallel FE space.
Definition at line 18 of file FEMOperators.cpp.
~FEMOperators()
FEMOperators::~FEMOperators ()
Destructor.
Definition at line 22 of file FEMOperators.cpp.
Member Function Documentation
FormLinearSystem()
void FEMOperators::FormLinearSystem (std::unique_ptr< mfem::ParBilinearForm > & K, mfem::Array< int > & boundary_dofs, mfem::ParGridFunction & x, mfem::ParLinearForm & b, mfem::HypreParMatrix & A, mfem::HypreParVector & X, mfem::HypreParVector & B)
Form the linear system A·X = B.
Combines stiffness/mass matrices with boundary conditions, extracts the Hypre system matrix and RHS vector, and maps the solution grid-function x into true DOFs.
Parameters
K Bilinear form (stiffness or mass).
boundary_dofs Essential DOFs.
x Solution grid-function.
b Linear form (load/forcing).
A Output system matrix.
X Output solution vector (true DOFs).
B Output RHS vector (true DOFs).
Definition at line 69 of file FEMOperators.cpp.
References B, boundary_dofs, and K.
Referenced by ElectrodePotential::AssembleSystem(), ElectrolytePotential::AssembleSystem(), ElectrolytePotential::SetupField(), ElectrodeCahnHilliard::SetupField(), ElectrolyteDiffusion::SetupField(), ElectrodePotential::SetupField(), ElectrodeCahnHilliard::UpdateConcentration(), ElectrodeDiffusion::UpdateConcentration(), ElectrolyteDiffusion::UpdateConcentration(), ElectrodePotential::UpdatePotential(), and ElectrolytePotential::UpdatePotential().
FormSystemMatrix()
void FEMOperators::FormSystemMatrix (std::unique_ptr< mfem::ParBilinearForm > & M, mfem::Array< int > & boundary_dofs, mfem::HypreParMatrix & A)
Form the Hypre system matrix from a bilinear form.
Applies essential boundary DOFs, enforcing homogeneous Dirichlet conditions, and exports the final system matrix into A.
Parameters
M Mass/stiffness bilinear form.
boundary_dofs List of essential DOFs.
A Output HypreParMatrix system matrix.
Definition at line 60 of file FEMOperators.cpp.
References boundary_dofs, and M.
Referenced by ElectrodeCahnHilliard::SetupField(), ElectrodeDiffusion::SetupField(), and ElectrolyteDiffusion::SetupField().
InitializeForceTerm()
void FEMOperators::InitializeForceTerm (mfem::Coefficient & coef, std::unique_ptr< mfem::ParLinearForm > & B)
Initialize a force (linear) form.
Constructs and assembles a ParLinearForm using coefficient coef.
Parameters
coef Coefficient for the force term.
B Output unique_ptr to the linear form.
Definition at line 46 of file FEMOperators.cpp.
References B, coef, and local_fespace.
Referenced by ElectrolytePotential::SetupField(), ElectrodeCahnHilliard::SetupField(), ElectrodePotential::SetupField(), and ElectrodeDiffusion::UpdateConcentration().
InitializeMassMatrix()
void FEMOperators::InitializeMassMatrix (mfem::Coefficient & coef, std::unique_ptr< mfem::ParBilinearForm > & M)
Initialize a mass bilinear form.
Creates a ParBilinearForm on the FE space using coefficient coef and performs domain integration to build the mass matrix structure.
Parameters
coef Scalar or spatial coefficient.
M Output unique_ptr to the mass bilinear form.
Definition at line 25 of file FEMOperators.cpp.
References coef, local_fespace, and M.
Referenced by ElectrodeCahnHilliard::SetupField(), ElectrodeDiffusion::SetupField(), and ElectrolyteDiffusion::SetupField().
InitializeStiffnessMatrix()
void FEMOperators::InitializeStiffnessMatrix (mfem::Coefficient & coef, std::unique_ptr< mfem::ParBilinearForm > & K)
Initialize a stiffness bilinear form.
Creates and assembles a diffusion/gradient operator using the provided coefficient coef.
Parameters
coef Coefficient used for the stiffness matrix.
K Output unique_ptr to the stiffness bilinear form.
Definition at line 35 of file FEMOperators.cpp.
References coef, K, and local_fespace.
Referenced by ElectrolytePotential::SetupField(), ElectrodeCahnHilliard::SetupField(), ElectrodeDiffusion::SetupField(), ElectrolyteDiffusion::SetupField(), and ElectrodePotential::SetupField().
SolverConditions() [1/2]
void FEMOperators::SolverConditions (mfem::CGSolver & solver, mfem::Solver & preconditioner)
Configure solver/preconditioner pair (matrix-free).
Useful when matrix is already installed in the solver.
Parameters
solver CG solver.
preconditioner Preconditioner.
Definition at line 108 of file FEMOperators.cpp.
SolverConditions() [2/2]
void FEMOperators::SolverConditions (mfem::HypreParMatrix & Mmat, mfem::CGSolver & solver, mfem::Solver & preconditioner)
Configure solver and preconditioner for a given system matrix.
Sets tolerances, iteration caps, and attaches preconditioner to solver.
Parameters
Mmat System matrix.
solver Hypre CG solver to configure.
preconditioner Preconditioner (Jacobi, Gauss-Seidel, HypreSmoother, etc.).
Definition at line 97 of file FEMOperators.cpp.
Referenced by ElectrolytePotential::SetupField(), ElectrodeCahnHilliard::SetupField(), ElectrodeDiffusion::SetupField(), and ElectrolyteDiffusion::SetupField().
Update() [1/2]
void FEMOperators::Update (std::unique_ptr< mfem::ParBilinearForm > & B)
Reassemble a ParBilinearForm.
Parameters
B Bilinear form to update.
Definition at line 87 of file FEMOperators.cpp.
References B.
Update() [2/2]
void FEMOperators::Update (std::unique_ptr< mfem::ParLinearForm > & B)
Reassemble a ParLinearForm.
Parameters
B Linear form to update.
Definition at line 77 of file FEMOperators.cpp.
References B.
Referenced by ElectrodePotential::AssembleSystem(), ElectrolytePotential::AssembleSystem(), ElectrolytePotential::SetupField(), ElectrodeCahnHilliard::UpdateConcentration(), ElectrodeDiffusion::UpdateConcentration(), and ElectrolyteDiffusion::UpdateConcentration().
Member Data Documentation
B
std::unique_ptr<mfem::ParLinearForm> FEMOperators::B private
Force/forcing term.
Definition at line 165 of file FEMOperators.hpp.
Referenced by FormLinearSystem(), InitializeForceTerm(), Update(), and Update().
boundary_dofs
mfem::Array<int> FEMOperators::boundary_dofs
Essential boundary DOFs.
Definition at line 150 of file FEMOperators.hpp.
Referenced by FormLinearSystem(), and FormSystemMatrix().
coef
mfem::GridFunctionCoefficient* FEMOperators::coef = nullptr private
Coefficient wrapper for grid-functions.
Definition at line 167 of file FEMOperators.hpp.
Referenced by InitializeForceTerm(), InitializeMassMatrix(), and InitializeStiffnessMatrix().
fespace
std::shared_ptr<mfem::ParFiniteElementSpace> FEMOperators::fespace private
FE space (shared_ptr).
Definition at line 157 of file FEMOperators.hpp.
K
std::shared_ptr<mfem::ParBilinearForm> FEMOperators::K
Assembled stiffness form.
Definition at line 148 of file FEMOperators.hpp.
Referenced by FormLinearSystem(), and InitializeStiffnessMatrix().
local_fespace
mfem::ParFiniteElementSpace* FEMOperators::local_fespace = nullptr private
Local FE space (alias).
Definition at line 159 of file FEMOperators.hpp.
Referenced by InitializeForceTerm(), InitializeMassMatrix(), and InitializeStiffnessMatrix().
M
mfem::ParBilinearForm* FEMOperators::M = nullptr private
Mass matrix (raw pointer).
Definition at line 164 of file FEMOperators.hpp.
Referenced by FormSystemMatrix(), and InitializeMassMatrix().
pmesh
mfem::ParMesh* FEMOperators::pmesh = nullptr private
Parallel mesh.
Definition at line 156 of file FEMOperators.hpp.
raw_fespace
mfem::ParFiniteElementSpace* FEMOperators::raw_fespace = nullptr private
Raw FE space pointer.
Definition at line 158 of file FEMOperators.hpp.
temp_ps
mfem::ParGridFunction* FEMOperators::temp_ps = nullptr private
Temporary phase-field grid-function.
Definition at line 166 of file FEMOperators.hpp.
X1v
mfem::HypreParVector FEMOperators::X1v
Scratch true-DoF vector.
Definition at line 149 of file FEMOperators.hpp.
The documentation for this class was generated from the following files:
include/FEMOperators.hpp
src/FEMOperators.cpp