BESFEM: src/Initialize_Geometry.cpp File Reference
Initialize_Geometry.cpp File Reference
#include "../include/Initialize_Geometry.hpp"
#include "../include/Constants.hpp"
#include "../include/readtiff.h"
#include "../include/SimTypes.hpp"
#include "../include/dist_solver.hpp"
#include "mfem.hpp"
#include <tiffio.h>
#include <fstream>
#include <iostream>
#include <stdexcept>
#include <vector>
#include <queue>
#include <cstdint>
Functions
static void KeepOnlyConnectedToBoundary_2D (std::vector< uint8_t > &solid, int nx, int ny, bool eight_conn, bool seed_all_boundaries=true, int seed_side=-1)
static void KeepOnlyConnectedToBoundary_3D (std::vector< uint8_t > &solid, int nx, int ny, int nz, bool twenty_six_conn, bool seed_all_boundaries=true, int seed_face=-1)
Function Documentation
KeepOnlyConnectedToBoundary_2D()
static void KeepOnlyConnectedToBoundary_2D (std::vector< uint8_t > & solid, int nx, int ny, bool eight_conn, bool seed_all_boundaries = true, int seed_side = -1) static
Definition at line 30 of file Initialize_Geometry.cpp.
Referenced by Initialize_Geometry::ComputePDEFilter(), and Initialize_Geometry::ComputePDEFilterLabel().
KeepOnlyConnectedToBoundary_3D()
static void KeepOnlyConnectedToBoundary_3D (std::vector< uint8_t > & solid, int nx, int ny, int nz, bool twenty_six_conn, bool seed_all_boundaries = true, int seed_face = -1) static
Definition at line 79 of file Initialize_Geometry.cpp.
Referenced by Initialize_Geometry::ComputePDEFilter(), and Initialize_Geometry::ComputePDEFilterLabel().