BESFEM: MaterialProperties Namespace Reference
MaterialProperties Namespace Reference
Material-dependent electrochemical property models.
Functions
static double GetTableValues (double x, const mfem::Vector &ticks, const mfem::Vector &data)
static double NMC_OCV (double c)
static double NMC_mu (double c)
static double NMC_i0 (double c)
static double NMC_diff (double c)
static double LFP_i0 (double c)
static double LFP_OCV (double c)
static double LFP_mu (double c)
static double LFP_dmu_dc (double c)
static double LFP_diff (double c)
static double LFP_Mob (double c)
double LFP_ChpValue (double c)
Return the tabulated LFP chemical-potential value.
static double Graphite_OCV (double c)
double OCV (sim::MaterialType material, double c)
Return the open-circuit voltage (OCV).
static double Graphite_i0 (double c)
double ExchangeCurrentDensity (sim::MaterialType material, double c)
Return the exchange current density.
static double Electrolyte_diff (double c)
double Diffusivity (sim::MaterialType material, double c)
Return the lithium diffusivity.
static double Graphite_Mob (double c)
double Mobility (sim::MaterialType material, double c)
Return the mobility.
static double Graphite_mu (double c)
double ChemicalPotential (sim::MaterialType material, double c)
Return the chemical potential.
static double GraphiteConductivity (double c)
static double NMCConductivity (double c)
static double LFPConductivity (double c)
double Conductivity (sim::MaterialType material, double c)
Return the electrical conductivity.
double SiteDensity (sim::MaterialType material)
Return the lithium site density.
Detailed Description
Material-dependent electrochemical property models.
The functions in this namespace provide constitutive relationships for each supported electrode material. These properties are used by the reaction, concentration, and potential solvers.
Function Documentation
ChemicalPotential()
double MaterialProperties::ChemicalPotential (sim::MaterialType material, double c)
Return the chemical potential.
Parameters
material Electrode material.
c Normalized lithium concentration.
Returns
Chemical potential.
Definition at line 369 of file MaterialProperties.cpp.
References sim::Graphite, Graphite_mu(), sim::LFP, LFP_mu(), sim::NMC, and NMC_mu().
Referenced by UpdateAnodePairChemicalPotentials(), UpdateCathodePairChemicalPotentials(), and ElectrodeCahnHilliard::UpdateConcentration().
Conductivity()
double MaterialProperties::Conductivity (sim::MaterialType material, double c)
Return the electrical conductivity.
Parameters
material Electrode material.
c Normalized lithium concentration.
Returns
Electrical conductivity.
Definition at line 403 of file MaterialProperties.cpp.
References sim::Graphite, GraphiteConductivity(), sim::LFP, LFPConductivity(), sim::NMC, and NMCConductivity().
Referenced by ElectrodePotential::ParticleConductivityMulti(), and ElectrodePotential::SetupField().
Diffusivity()
double MaterialProperties::Diffusivity (sim::MaterialType material, double c)
Return the lithium diffusivity.
Parameters
material Electrode material.
c Normalized lithium concentration.
Returns
Diffusivity.
Definition at line 282 of file MaterialProperties.cpp.
References sim::Electrolyte, Electrolyte_diff(), sim::LFP, LFP_diff(), sim::NMC, and NMC_diff().
Referenced by ElectrodeDiffusion::UpdateConcentration(), and ElectrolyteDiffusion::UpdateConcentration().
Electrolyte_diff()
static double MaterialProperties::Electrolyte_diff (double c) static
Definition at line 277 of file MaterialProperties.cpp.
References Constants::D0.
Referenced by Diffusivity().
ExchangeCurrentDensity()
double MaterialProperties::ExchangeCurrentDensity (sim::MaterialType material, double c)
Return the exchange current density.
Parameters
material Electrode material.
c Normalized lithium concentration.
Returns
Exchange current density.
Definition at line 258 of file MaterialProperties.cpp.
References sim::Graphite, Graphite_i0(), sim::LFP, LFP_i0(), sim::NMC, and NMC_i0().
Referenced by Reaction::ExchangeCurrentDensity().
GetTableValues()
static double MaterialProperties::GetTableValues (double x, const mfem::Vector & ticks, const mfem::Vector & data) static
Definition at line 10 of file MaterialProperties.cpp.
Referenced by Graphite_i0(), Graphite_Mob(), Graphite_mu(), Graphite_OCV(), LFP_ChpValue(), and LFP_OCV().
Graphite_i0()
static double MaterialProperties::Graphite_i0 (double c) static
Definition at line 232 of file MaterialProperties.cpp.
References GetTableValues().
Referenced by ExchangeCurrentDensity().
Graphite_Mob()
static double MaterialProperties::Graphite_Mob (double c) static
Definition at line 301 of file MaterialProperties.cpp.
References GetTableValues().
Referenced by Mobility().
Graphite_mu()
static double MaterialProperties::Graphite_mu (double c) static
Definition at line 344 of file MaterialProperties.cpp.
References GetTableValues().
Referenced by ChemicalPotential().
Graphite_OCV()
static double MaterialProperties::Graphite_OCV (double c) static
Definition at line 188 of file MaterialProperties.cpp.
References GetTableValues(), and OCV().
Referenced by OCV().
GraphiteConductivity()
static double MaterialProperties::GraphiteConductivity (double c) static
Definition at line 387 of file MaterialProperties.cpp.
Referenced by Conductivity().
LFP_ChpValue()
double MaterialProperties::LFP_ChpValue (double c)
Return the tabulated LFP chemical-potential value.
This function evaluates the tabulated chemical-potential curve used for lithium iron phosphate (LFP).
Parameters
c Normalized lithium concentration.
Returns
LFP chemical-potential value.
Definition at line 163 of file MaterialProperties.cpp.
References GetTableValues().
LFP_diff()
static double MaterialProperties::LFP_diff (double c) static
Definition at line 111 of file MaterialProperties.cpp.
Referenced by Diffusivity().
LFP_dmu_dc()
static double MaterialProperties::LFP_dmu_dc (double c) static
Definition at line 101 of file MaterialProperties.cpp.
References LFP_mu().
LFP_i0()
static double MaterialProperties::LFP_i0 (double c) static
Definition at line 53 of file MaterialProperties.cpp.
Referenced by ExchangeCurrentDensity().
LFP_Mob()
static double MaterialProperties::LFP_Mob (double c) static
Definition at line 138 of file MaterialProperties.cpp.
Referenced by Mobility().
LFP_mu()
static double MaterialProperties::LFP_mu (double c) static
Definition at line 93 of file MaterialProperties.cpp.
References Constants::Frd, and LFP_OCV().
Referenced by ChemicalPotential(), and LFP_dmu_dc().
LFP_OCV()
static double MaterialProperties::LFP_OCV (double c) static
Definition at line 68 of file MaterialProperties.cpp.
References GetTableValues().
Referenced by LFP_mu(), and OCV().
LFPConductivity()
static double MaterialProperties::LFPConductivity (double c) static
Definition at line 397 of file MaterialProperties.cpp.
Referenced by Conductivity().
Mobility()
double MaterialProperties::Mobility (sim::MaterialType material, double c)
Return the mobility.
Parameters
material Electrode material.
c Normalized lithium concentration.
Returns
Mobility.
Definition at line 328 of file MaterialProperties.cpp.
References sim::Graphite, Graphite_Mob(), sim::LFP, and LFP_Mob().
Referenced by ElectrodeCahnHilliard::UpdateConcentration().
NMC_diff()
static double MaterialProperties::NMC_diff (double c) static
Definition at line 41 of file MaterialProperties.cpp.
Referenced by Diffusivity().
NMC_i0()
static double MaterialProperties::NMC_i0 (double c) static
Definition at line 35 of file MaterialProperties.cpp.
Referenced by ExchangeCurrentDensity().
NMC_mu()
static double MaterialProperties::NMC_mu (double c) static
Definition at line 29 of file MaterialProperties.cpp.
References Constants::Frd, and NMC_OCV().
Referenced by ChemicalPotential().
NMC_OCV()
static double MaterialProperties::NMC_OCV (double c) static
Definition at line 24 of file MaterialProperties.cpp.
Referenced by NMC_mu(), and OCV().
NMCConductivity()
static double MaterialProperties::NMCConductivity (double c) static
Definition at line 392 of file MaterialProperties.cpp.
Referenced by Conductivity().
OCV()
double MaterialProperties::OCV (sim::MaterialType material, double c)
Return the open-circuit voltage (OCV).
Parameters
material Electrode material.
c Normalized lithium concentration.
Returns
Open-circuit voltage (V).
Definition at line 213 of file MaterialProperties.cpp.
References sim::Graphite, Graphite_OCV(), sim::LFP, LFP_OCV(), sim::NMC, and NMC_OCV().
Referenced by CheckAnodeInitialBoundaryFromOCV(), CheckCathodeInitialBoundaryFromOCV(), Reaction::ExchangeCurrentDensity(), and Graphite_OCV().
SiteDensity()
double MaterialProperties::SiteDensity (sim::MaterialType material)
Return the lithium site density.
Parameters
material Electrode material.
Returns
Site density.
Definition at line 422 of file MaterialProperties.cpp.
References sim::Graphite, sim::LFP, and sim::NMC.
Referenced by Domain_Parameters::CalculateTargetCurrent(), Utils::ComputePairFlux(), ElectrodeCahnHilliard::UpdateConcentration(), and ElectrodeDiffusion::UpdateConcentration().