BESFEM: include/SimulationState.hpp File Reference
SimulationState.hpp File Reference
Defines runtime state containers for BESFEM simulations.
#include "mfem.hpp"
#include "BESFEM_All.hpp"
#include <memory>
#include <vector>
Classes
struct AnodeParticleState
Stores solver objects and fields for one anode particle group.
struct CathodeParticleState
Stores solver objects and fields for one cathode particle group.
struct SimulationState
Owns the runtime solvers and grid functions for a BESFEM simulation.
Functions
void InitializeFields (SimulationState &state, Initialize_Geometry &geometry, Domain_Parameters &domain_parameters, BoundaryConditions &bc, const SimulationConfig &cfg)
Allocate and initialize all simulation fields and solver objects.
void UpdateCathodePairChemicalPotentials (SimulationState &state, Initialize_Geometry &geometry, Domain_Parameters &domain_parameters)
Update pairwise cathode chemical-potential fields.
void UpdateAnodePairChemicalPotentials (SimulationState &state, Initialize_Geometry &geometry, Domain_Parameters &domain_parameters)
Update pairwise anode chemical-potential fields.
void Pairs (SimulationState &state, Initialize_Geometry &geometry, Domain_Parameters &domain_parameters, int j, std::vector< ConcentrationBase::PairCoupling > &pair_terms, int np, int t)
Build pairwise coupling terms for one particle.
Detailed Description
Defines runtime state containers for BESFEM simulations.
Definition in file SimulationState.hpp.
Function Documentation
InitializeFields()
void InitializeFields (SimulationState & state, Initialize_Geometry & geometry, Domain_Parameters & domain_parameters, BoundaryConditions & bc, const SimulationConfig & cfg)
Allocate and initialize all simulation fields and solver objects.
Creates concentration, potential, and reaction solvers according to the simulation configuration, allocates their associated grid functions, and initializes field values before the timestep loop begins.
Parameters
state Simulation state object to populate.
geometry Geometry and finite-element-space handler.
domain_parameters Domain fields and global quantities.
bc Boundary-condition handler.
cfg Simulation configuration.
Definition at line 295 of file SimulationState.cpp.
References sim::ANODE, SimulationState::anode_out, SimulationState::anode_particles, SimulationState::anode_potential, sim::CATHODE, SimulationState::cathode_out, SimulationState::cathode_particles, SimulationState::cathode_potential, SimulationState::CnA_gf_psi, SimulationState::CnC_gf_psi, SimulationState::CnE_gf, SimulationState::CnE_gf_psi, SimulationState::CnP_together, sim::Electrolyte, SimulationState::electrolyte_concentration, SimulationState::electrolyte_potential, sim::Graphite, Domain_Parameters::gtPse, sim::HALF, SimulationConfig::half_electrode, SimulationConfig::init_BvA, SimulationConfig::init_BvC, SimulationConfig::init_BvE, SimulationConfig::init_CnE, Constants::init_Rxn, InitializeAnodeParticles(), InitializeCathodeParticles(), InitializePairWorkspaces(), SimulationConfig::mode, sim::NMC, Initialize_Geometry::parfespace, SimulationState::phA_gf, SimulationState::phC_gf, SimulationState::phE_gf, Domain_Parameters::ps, Domain_Parameters::psA, Domain_Parameters::psC, Domain_Parameters::pse, Domain_Parameters::psi, SimulationState::reaction, and SimulationState::Rxn_gf.
Referenced by main().
Pairs()
void Pairs (SimulationState & state, Initialize_Geometry & geometry, Domain_Parameters & domain_parameters, int j, std::vector< ConcentrationBase::PairCoupling > & pair_terms, int np, int t)
Build pairwise coupling terms for one particle.
Populates the pair_terms vector with the interface weights, chemical potentials, and accumulated pair fields needed by the concentration solver for particle-particle coupling.
Parameters
state Simulation state containing pairwise workspaces.
geometry Geometry and finite-element-space handler.
domain_parameters Domain fields and pairwise coupling masks.
j Particle index for which pair terms are assembled.
pair_terms Output vector of pairwise coupling structures.
np Number of particles in the current electrode group.
t Current timestep index.
Definition at line 385 of file SimulationState.cpp.
References Domain_Parameters::AvP_Pairs, ConcentrationBase::PairCoupling::grad_psi, ConcentrationBase::PairCoupling::mu_nbr, SimulationState::mu_pair_a, SimulationState::mu_pair_b, ConcentrationBase::PairCoupling::mu_self, SimulationState::sum_pairs, ConcentrationBase::PairCoupling::sum_part, ConcentrationBase::PairCoupling::weight, and Domain_Parameters::WeightPairs.
Referenced by main().
UpdateAnodePairChemicalPotentials()
void UpdateAnodePairChemicalPotentials (SimulationState & state, Initialize_Geometry & geometry, Domain_Parameters & domain_parameters)
Update pairwise anode chemical-potential fields.
Computes chemical-potential workspaces used for anode particle-particle coupling terms.
Parameters
state Simulation state containing anode particle fields.
geometry Geometry and finite-element-space handler.
domain_parameters Domain fields and pairwise coupling masks.
Definition at line 83 of file SimulationState.cpp.
References SimulationState::anode_particles, Domain_Parameters::AvP_Pairs, MaterialProperties::ChemicalPotential(), SimulationState::mu_pair_a, SimulationState::mu_pair_b, and Initialize_Geometry::nV.
Referenced by main().
UpdateCathodePairChemicalPotentials()
void UpdateCathodePairChemicalPotentials (SimulationState & state, Initialize_Geometry & geometry, Domain_Parameters & domain_parameters)
Update pairwise cathode chemical-potential fields.
Computes chemical-potential workspaces used for cathode particle-particle coupling terms.
Parameters
state Simulation state containing cathode particle fields.
geometry Geometry and finite-element-space handler.
domain_parameters Domain fields and pairwise coupling masks.
Definition at line 50 of file SimulationState.cpp.
References Domain_Parameters::AvP_Pairs, SimulationState::cathode_particles, MaterialProperties::ChemicalPotential(), SimulationState::mu_pair_a, SimulationState::mu_pair_b, and Initialize_Geometry::nV.
Referenced by main().