BESFEM: include/SimulationConfig.hpp File Reference
SimulationConfig.hpp File Reference
Defines the simulation configuration used by BESFEM.
#include "SimTypes.hpp"
#include "Constants.hpp"
#include <string>
#include <vector>
Classes
struct SimulationConfig
Stores all user-configurable simulation settings.
Functions
SimulationConfig ParseSimulationArgs (int argc, char *argv[])
Parse command-line arguments and configuration file.
void ValidateConfig (const SimulationConfig &cfg, int argc, char *argv[])
Validate the simulation configuration.
void PrintAvailableSimulationOptions ()
Print the available command-line simulation options.
Detailed Description
Defines the simulation configuration used by BESFEM.
Definition in file SimulationConfig.hpp.
Function Documentation
ParseSimulationArgs()
SimulationConfig ParseSimulationArgs (int argc, char * argv[])
Parse command-line arguments and configuration file.
Reads the simulation configuration file together with any command-line overrides and returns the resulting configuration object.
Parameters
argc Number of command-line arguments.
argv Command-line argument array.
Returns
Fully populated simulation configuration.
Definition at line 256 of file SimulationConfig.cpp.
References sim::ANODE, ApplyConfigFile(), sim::CATHODE, SimulationConfig::combine_particle_groups, SimulationConfig::config_file, sim::FULL, sim::HALF, SimulationConfig::half_electrode, SimulationConfig::mesh_file, SimulationConfig::mode, SimulationConfig::order, PrintAvailableSimulationOptions(), sim::STEPS, SimulationConfig::stop_mode, and sim::VOLTAGE.
Referenced by main().
PrintAvailableSimulationOptions()
void PrintAvailableSimulationOptions ()
Print the available command-line simulation options.
Definition at line 596 of file SimulationConfig.cpp.
Referenced by ParseSimulationArgs().
ValidateConfig()
void ValidateConfig (const SimulationConfig & cfg, int argc, char * argv[])
Validate the simulation configuration.
Performs consistency checks on the supplied configuration and reports invalid or incompatible options.
Parameters
cfg Simulation configuration to validate.
argc Number of command-line arguments.
argv Command-line argument array.
Definition at line 420 of file SimulationConfig.cpp.
References SimulationConfig::anode_materials, sim::CATHODE, SimulationConfig::cathode_materials, CheckAnodeInitialBoundaryFromOCV(), CheckCathodeInitialBoundaryFromOCV(), CheckParticleStoichiometry(), SimulationConfig::Cr, SimulationConfig::dh, SimulationConfig::dt, sim::FULL, SimulationConfig::gc, sim::HALF, SimulationConfig::half_electrode, SimulationConfig::init_anode_particles, SimulationConfig::init_BvA, SimulationConfig::init_BvC, SimulationConfig::init_BvE, SimulationConfig::init_cathode_particles, SimulationConfig::init_CnE, IsAnodeMaterial(), IsCathodeMaterial(), SimulationConfig::mesh_file, SimulationConfig::mode, SimulationConfig::num_timesteps, sim::STEPS, SimulationConfig::stop_mode, SimulationConfig::VCut, and sim::VOLTAGE.
Referenced by main().