BESFEM: src/SimulationConfig.cpp File Reference
SimulationConfig.cpp File Reference
#include "../include/SimulationConfig.hpp"
#include "../include/MaterialProperties.hpp"
#include "mfem.hpp"
#include <cstring>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <unordered_map>
#include <vector>
Functions
static std::string Trim (const std::string &s)
static std::vector< std::string > SplitString (const std::string &text, char delimiter)
static std::unordered_map< std::string, std::string > ReadConfigFile (const std::string &filename)
static bool HasKey (const std::unordered_map< std::string, std::string > &data, const std::string &key)
static std::string GetValue (const std::unordered_map< std::string, std::string > &data, const std::string &key)
static bool ParseBool (const std::string &value)
static sim::MaterialType ParseMaterial (const std::string &name)
static std::vector< sim::MaterialType > ParseMaterialList (const std::string &text)
static std::vector< double > ParseDoubleList (const std::string &text)
static sim::StopMode ParseStopMode (const std::string &value)
static void ApplyConfigFile (SimulationConfig &cfg)
SimulationConfig ParseSimulationArgs (int argc, char *argv[])
Parse command-line arguments and configuration file.
static bool IsCathodeMaterial (sim::MaterialType m)
static bool IsAnodeMaterial (sim::MaterialType m)
static void CheckCathodeInitialBoundaryFromOCV (const SimulationConfig &cfg)
static void CheckAnodeInitialBoundaryFromOCV (const SimulationConfig &cfg)
static void CheckParticleStoichiometry (const std::vector< double > &values, const std::string &name)
void ValidateConfig (const SimulationConfig &cfg, int argc, char *argv[])
Validate the simulation configuration.
void PrintAvailableSimulationOptions ()
Print the available command-line simulation options.
Function Documentation
ApplyConfigFile()
static void ApplyConfigFile (SimulationConfig & cfg) static
Definition at line 165 of file SimulationConfig.cpp.
References SimulationConfig::amr_levels, sim::ANODE, SimulationConfig::anode_materials, sim::CATHODE, SimulationConfig::cathode_materials, SimulationConfig::combine_particle_groups, SimulationConfig::config_file, SimulationConfig::Cr, SimulationConfig::dh, SimulationConfig::dt, sim::FULL, SimulationConfig::gc, GetValue(), sim::HALF, SimulationConfig::half_electrode, HasKey(), SimulationConfig::init_anode_particles, SimulationConfig::init_BvA, SimulationConfig::init_BvC, SimulationConfig::init_BvE, SimulationConfig::init_cathode_particles, SimulationConfig::init_CnE, SimulationConfig::mesh_file, SimulationConfig::mode, SimulationConfig::num_timesteps, ParseBool(), ParseDoubleList(), ParseMaterialList(), ParseStopMode(), ReadConfigFile(), SimulationConfig::stop_mode, SimulationConfig::VCut, and SimulationConfig::Vsr0.
Referenced by ParseSimulationArgs().
CheckAnodeInitialBoundaryFromOCV()
static void CheckAnodeInitialBoundaryFromOCV (const SimulationConfig & cfg) static
Definition at line 376 of file SimulationConfig.cpp.
References SimulationConfig::anode_materials, SimulationConfig::init_anode_particles, SimulationConfig::init_BvA, and MaterialProperties::OCV().
Referenced by ValidateConfig().
CheckCathodeInitialBoundaryFromOCV()
static void CheckCathodeInitialBoundaryFromOCV (const SimulationConfig & cfg) static
Definition at line 352 of file SimulationConfig.cpp.
References SimulationConfig::cathode_materials, SimulationConfig::init_BvC, SimulationConfig::init_cathode_particles, and MaterialProperties::OCV().
Referenced by ValidateConfig().
CheckParticleStoichiometry()
static void CheckParticleStoichiometry (const std::vector< double > & values, const std::string & name) static
Definition at line 400 of file SimulationConfig.cpp.
Referenced by ValidateConfig().
GetValue()
static std::string GetValue (const std::unordered_map< std::string, std::string > & data, const std::string & key) static
Definition at line 86 of file SimulationConfig.cpp.
Referenced by ApplyConfigFile().
HasKey()
static bool HasKey (const std::unordered_map< std::string, std::string > & data, const std::string & key) static
Definition at line 79 of file SimulationConfig.cpp.
Referenced by ApplyConfigFile().
IsAnodeMaterial()
static bool IsAnodeMaterial (sim::MaterialType m) static
Definition at line 348 of file SimulationConfig.cpp.
References sim::Graphite.
Referenced by ValidateConfig().
IsCathodeMaterial()
static bool IsCathodeMaterial (sim::MaterialType m) static
Definition at line 342 of file SimulationConfig.cpp.
References sim::LFP, and sim::NMC.
Referenced by ValidateConfig().
ParseBool()
static bool ParseBool (const std::string & value) static
Definition at line 100 of file SimulationConfig.cpp.
Referenced by ApplyConfigFile().
ParseDoubleList()
static std::vector< double > ParseDoubleList (const std::string & text) static
Definition at line 139 of file SimulationConfig.cpp.
References SplitString().
Referenced by ApplyConfigFile().
ParseMaterial()
static sim::MaterialType ParseMaterial (const std::string & name) static
Definition at line 111 of file SimulationConfig.cpp.
References sim::Electrolyte, sim::Graphite, sim::LFP, and sim::NMC.
Referenced by ParseMaterialList().
ParseMaterialList()
static std::vector< sim::MaterialType > ParseMaterialList (const std::string & text) static
Definition at line 127 of file SimulationConfig.cpp.
References ParseMaterial(), and SplitString().
Referenced by ApplyConfigFile().
ParseSimulationArgs()
SimulationConfig ParseSimulationArgs (int argc, char * argv[])
Parse command-line arguments and configuration file.
Reads the simulation configuration file together with any command-line overrides and returns the resulting configuration object.
Parameters
argc Number of command-line arguments.
argv Command-line argument array.
Returns
Fully populated simulation configuration.
Definition at line 256 of file SimulationConfig.cpp.
References sim::ANODE, ApplyConfigFile(), sim::CATHODE, SimulationConfig::combine_particle_groups, SimulationConfig::config_file, sim::FULL, sim::HALF, SimulationConfig::half_electrode, SimulationConfig::mesh_file, SimulationConfig::mode, SimulationConfig::order, PrintAvailableSimulationOptions(), sim::STEPS, SimulationConfig::stop_mode, and sim::VOLTAGE.
Referenced by main().
ParseStopMode()
static sim::StopMode ParseStopMode (const std::string & value) static
Definition at line 151 of file SimulationConfig.cpp.
References sim::STEPS, and sim::VOLTAGE.
Referenced by ApplyConfigFile().
PrintAvailableSimulationOptions()
void PrintAvailableSimulationOptions ()
Print the available command-line simulation options.
Definition at line 596 of file SimulationConfig.cpp.
Referenced by ParseSimulationArgs().
ReadConfigFile()
static std::unordered_map< std::string, std::string > ReadConfigFile (const std::string & filename) static
Definition at line 42 of file SimulationConfig.cpp.
References Trim().
Referenced by ApplyConfigFile().
SplitString()
static std::vector< std::string > SplitString (const std::string & text, char delimiter) static
Definition at line 23 of file SimulationConfig.cpp.
References Trim().
Referenced by ParseDoubleList(), and ParseMaterialList().
Trim()
static std::string Trim (const std::string & s) static
Definition at line 14 of file SimulationConfig.cpp.
Referenced by ReadConfigFile(), and SplitString().
ValidateConfig()
void ValidateConfig (const SimulationConfig & cfg, int argc, char * argv[])
Validate the simulation configuration.
Performs consistency checks on the supplied configuration and reports invalid or incompatible options.
Parameters
cfg Simulation configuration to validate.
argc Number of command-line arguments.
argv Command-line argument array.
Definition at line 420 of file SimulationConfig.cpp.
References SimulationConfig::anode_materials, sim::CATHODE, SimulationConfig::cathode_materials, CheckAnodeInitialBoundaryFromOCV(), CheckCathodeInitialBoundaryFromOCV(), CheckParticleStoichiometry(), SimulationConfig::Cr, SimulationConfig::dh, SimulationConfig::dt, sim::FULL, SimulationConfig::gc, sim::HALF, SimulationConfig::half_electrode, SimulationConfig::init_anode_particles, SimulationConfig::init_BvA, SimulationConfig::init_BvC, SimulationConfig::init_BvE, SimulationConfig::init_cathode_particles, SimulationConfig::init_CnE, IsAnodeMaterial(), IsCathodeMaterial(), SimulationConfig::mesh_file, SimulationConfig::mode, SimulationConfig::num_timesteps, sim::STEPS, SimulationConfig::stop_mode, SimulationConfig::VCut, and sim::VOLTAGE.
Referenced by main().