title: BESFEM
description: Battery Electrode Simulation Finite Electrode
remote_theme: just-the-docs/just-the-docs
color_scheme: teal
plugins:
  - jekyll-remote-theme
url : https://github.com/HCY-Group/BESFEM.git
url: https://github.com/trahman64/BESFEM.git
baseurl: "/BESFEM"
aux_links:
  GitHub Repository: https://github.com/HCY-Group/BESFEM
